package pe.egcc.uni.eureka.view;

import javax.swing.JInternalFrame;
import pe.egcc.uni.eureka.model.EmpleadoModel;
import pe.egcc.uni.eureka.util.Session;

/**
 *
 * @author Eric Gustavo Coronel Castillo
 * @email gcoronelc@gmail.com
 * @blog gcoronelc.blogspot.com
 * @date 26/12/2015
 *
 */
public class MainView extends javax.swing.JFrame {

  /**
   * Creates new form MainView
   */
  public MainView() {
    initComponents();
    this.setExtendedState(MAXIMIZED_BOTH);
    establecerTitulo();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    exitMenuItem = new javax.swing.JMenuItem();
    menuProcesos = new javax.swing.JMenu();
    menuTablas = new javax.swing.JMenu();
    menuTablasClientes = new javax.swing.JMenuItem();
    menuConsultas = new javax.swing.JMenu();
    menuReportes = new javax.swing.JMenu();
    menuUtil = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("EUREKA APP");

    fileMenu.setMnemonic('f');
    fileMenu.setText("File");

    exitMenuItem.setMnemonic('x');
    exitMenuItem.setText("Exit");
    exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    menuProcesos.setText("Procesos");
    menuBar.add(menuProcesos);

    menuTablas.setText("Tablas");

    menuTablasClientes.setText("Clientes");
    menuTablasClientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuTablasClientesActionPerformed(evt);
      }
    });
    menuTablas.add(menuTablasClientes);

    menuBar.add(menuTablas);

    menuConsultas.setText("Consultas");
    menuBar.add(menuConsultas);

    menuReportes.setText("Reportes");
    menuBar.add(menuReportes);

    menuUtil.setText("Util");
    menuBar.add(menuUtil);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

  private void menuTablasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasClientesActionPerformed
    cargarVentaInterna(MantClientesView.class);
  }//GEN-LAST:event_menuTablasClientesActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenuItem exitMenuItem;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuConsultas;
  private javax.swing.JMenu menuProcesos;
  private javax.swing.JMenu menuReportes;
  private javax.swing.JMenu menuTablas;
  private javax.swing.JMenuItem menuTablasClientes;
  private javax.swing.JMenu menuUtil;
  // End of variables declaration//GEN-END:variables

  private void establecerTitulo() {
    EmpleadoModel model;
    model = (EmpleadoModel) Session.get("usuario");
    String titulo = "EUREKA APP [Usuario:"
            + model.getNombre() + "]";
    this.setTitle(titulo);
  }

  private void cargarVentaInterna(Class<?> aClass) {
    try {
      JInternalFrame view = null;
      // Encontrar un formulario en el panel
      for (JInternalFrame frame : desktopPane.getAllFrames()) {
        if (aClass.isInstance(frame)) {
          view = frame;
          break;
        }
      }
      // Si no lo encuentro, creao la instancia
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
      }
      // Activar el formulario
      view.setVisible(true);
      view.setSelected(true);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

}
