/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.uni.eureka.view;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import pe.egcc.uni.eureka.db.AccesoDB;
import util.ReportViewInternal;

/**
 *
 * @author Administrador
 */
public class ReporteMovimientos extends javax.swing.JInternalFrame {

  /**
   * Creates new form ReporteMovimientos
   */
  public ReporteMovimientos() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtCuenta = new javax.swing.JTextField();
    btnProcesar = new javax.swing.JButton();
    panelReporte = new javax.swing.JPanel();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE MOVIMIENTOS");

    jLabel1.setText("Cuenta:");

    btnProcesar.setText("Procesar");
    btnProcesar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProcesarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
    panelReporte.setLayout(panelReporteLayout);
    panelReporteLayout.setHorizontalGroup(
      panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelReporteLayout.setVerticalGroup(
      panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 367, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnProcesar)
        .addContainerGap(495, Short.MAX_VALUE))
      .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1)
          .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
    Connection cn = null;
    try {
      // Usando el archivo JRXML y el objeto Connection
      cn = AccesoDB.getConnection();
      // Parametros
      Map parms = new HashMap();
      String cuenta = txtCuenta.getText();
      parms.put("CUENTA", cuenta);
      // Leer el compilado
      String archivoReporte = "/pe/egcc/uni/eureka/reports/ReporteMovimientos.jasper";
      InputStream inputStream = getClass().getResourceAsStream(archivoReporte);
      JasperReport jasperReport;
      jasperReport =  (JasperReport) JRLoader.loadObject(inputStream);
      // Cargar datos
      JasperPrint jasperPrint;
      jasperPrint = JasperFillManager.fillReport(jasperReport, parms, cn);
      // Cargar el reporte
      ReportViewInternal view = new ReportViewInternal();
      view.setReporte(jasperPrint);
      view.setTitle("CUENTA: " + cuenta);
      panelReporte.removeAll();
      panelReporte.add(view);
      view.setMaximum(true);
      view.setMaximizable(false);
      view.setIconifiable(false);
      view.setClosable(false);      
      view.setVisible(true);
      //view.pack();
      
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      try {
        cn.close();
      } catch (Exception e) {
      }
    }
  }//GEN-LAST:event_btnProcesarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnProcesar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel panelReporte;
  private javax.swing.JTextField txtCuenta;
  // End of variables declaration//GEN-END:variables
}
